### ISSUE TITLE
Lab hours table crashes website on mobile Safari

### ISSUE THREAD

**Issue by robertnperalta** [UCLA-IEEE/ieeebruins.com#79]
**Description**
When a user on iPhone scrolls to the point where the lab hours table would be rendered, the table does not render, instead hanging until the page refreshes. This repeats a few times until the browser refuses to load the page, complaining that "A Problem Repeatedly Occurred" (Safari) or "Can't open this page" (Chrome). Reproduced on both Safari and Chrome. First reported 11/2021.

**Steps to Reproduce**
1. Go to `ieeebruins.com`
2. Scroll down to the bottom of the page where lab hour table is
3. See error

**Expected Behavior**
Lab hours table should render normally.

**Actual Behavior**
Page crashes repeatedly.

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser: Safari, Chrome
 - Device: Mobile

**Comment by paulzzy** [comment]
As of Safari 17.4.1, the lab hours table displays correct on iOS Safari. Not sure if it's because of a code change on our end or a change in Safari's code.
